improve domain recon + update related scripts where used (#356)
* improve domain recon + update related scripts where used

this will allow to users set their extended/custom tld(s) lists and mute/point to extended tld lists to retrieve, or not leak server ip to tldextract each time and they can update tld list from tldextract by cron

right now it not support for example urls wtih .bit tld, so this fixes it :)

```
core.errors.ObservableValidationError: http://X.bit/X/X.php was not recognized as a viable datatype
```

* Update utils.py