webgui 500 - AttributeError: 'AnonymousUserMixin' object has no attribute 'has_role'
fixing this it will redirect to login page instead of give error 500

```
 File "/opt/yeti/core/auth/local/views.py", line 51, in new_group
 if current_user.has_role('admin') and current_user.is_active:
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'AnonymousUserMixin' object has no attribute 'has_role'
```