Fix investigations if no user input
if user press import, but not provided any input by default app throw an error, this forward back and flash msg about input required


no debug
```
Bad Request
The browser (or proxy) sent a request that this server could not understand.
```

```
BadRequestKeyError: 400 Bad Request: KeyError: 'file'
```